In [72]:
import pandas as pd 
import numpy as np
from numpy.linalg import norm
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer
ingr_ns=pd.read_csv('tabellen/data_ingr.csv')
ingr_schoon=pd.read_csv('tabellen/data_ingr_clean.csv')
data_recepten = pd.read_csv('tabellen/data_recipes.csv')
recipes = pd.read_csv('tabellen/Recepten_kiezen_gescheiden.csv') # Onze lijst van recepten die we wel en niet lekker vinden
recipes_wel = recipes[:80] # DataFrame met alle recpeten die wij lekker vinden
recipes_niet = recipes[80:] # DataFrame met alle recepten die wij niet lekker vinden

In [59]:
# import csv
# with open('tabellen/Recepten_kiezen_f.csv', newline='') as csvfile:
#     csvlezer = csv.reader(csvfile, delimiter=',', quotechar='"')
#     for x in csvlezer:
#         x = recipes
# recipes[117:123]

# recipes

In [60]:
onze_ns = ingr_ns[ingr_ns['recipe'].isin(recipes['title'])] # DataFrame van de ongeschoonde data met alle ingredienten van onze gekozen gerechten
onze_schoon = ingr_schoon[ingr_schoon['recipe'].isin(recipes['title'])] # DataFrame van de opgeschoonde data met alle ingredienten van onze gekozen gerechten


In [61]:
cosine1 = np.dot([1,1,1],[1,0,0])/(norm([1,1,1])*norm([1,0,0]))
#cosine1 = np.dot([1,1,1,1,1,1],[1,1,0,1,0,0])/(norm([1,1,1,1,1,1])*norm([1,1,0,1,0,0]))
cosine2 = np.dot([1,1,1],[1,1,0])/(norm([1,1,1])*norm([1,1,0]))
#cosine2 = np.dot([1,1,1,1,1,1],[0,0,1,0,0,0])/(norm([1,1,1,1,1,1])*norm([0,0,1,0,0,0]))
cosine3 = np.dot([1,1,1,1,1,1],[0,0,1,1,0,0])/(norm([1,1,1,1,1,1])*norm([0,0,1,1,0,0]))
print(cosine1)
print(cosine2)
print(cosine3)

0.5773502691896258
0.8164965809277259
0.5773502691896258


In [184]:
fav = ['melk','ei','water']
rec1 = ['water', 'appel']
rec2 = ['water','ei']
count_vectorizer = CountVectorizer()
fav_matrix = count_vectorizer.fit_transform(fav)
rec1_matrix = count_vectorizer.transform(rec1)
rec2_matrix = count_vectorizer.transform(rec2)
print('fav_matrix:\n',fav_matrix.toarray())
print('rec1_matrix:\n',rec1_matrix.toarray())
print('rec2_matrix:\n',rec2_matrix.toarray())
s = cosine_similarity(np.ones(np.size(rec1_matrix.toarray())).reshape(1,-1), rec1_matrix.reshape(1,-1))
t = cosine_similarity(np.ones(np.size(rec2_matrix.toarray())).reshape(1,-1), rec2_matrix.reshape(1,-1))
print('cosine_similarity met rec1: ', s[0][0])
print('cosine_similarity met rec2: ', t[0][0])

print('np.ones:\n',np.ones(np.size(rec1_matrix.toarray())).reshape(1,-1))
print('reshape(1,-1)\n', rec1_matrix.reshape(1,-1).toarray())

fav_matrix:
 [[0 1 0]
 [1 0 0]
 [0 0 1]]
rec1_matrix:
 [[0 0 1]
 [0 0 0]]
rec2_matrix:
 [[0 0 1]
 [1 0 0]]
cosine_similarity met rec1:  0.4082482904638631
cosine_similarity met rec2:  0.5773502691896258
np.ones:
 [[1. 1. 1. 1. 1. 1.]]
reshape(1,-1)
 [[0 0 1 0 0 0]]


In [179]:
ingr_schoon['recipe']
ingr_schoon['ingredient'].loc[ingr_schoon['recipe']=='Kruidnoten in marsepein']
# a=[ingr_schoon['ingredient'].loc[ingr_schoon['recipe']==recept] for recept in recipes_wel['title']]
fav_recepten = recipes_wel['title'].tolist()
#a=np.array(list(set(ingr_schoon['ingredient'].loc[ingr_schoon['recipe'].isin(fav_recepten)])))

fav=list(set(ingr_schoon['ingredient'].loc[ingr_schoon['recipe'].isin(fav_recepten)]))
count_vectorizer = CountVectorizer()
fav_matrix = count_vectorizer.fit_transform(fav)
# for recept in ingr_schoon['recipe']:
#     if recept not in fav_recepten:
#         print(recept)
titel_lijst = []
[titel_lijst.append(recept) for recept in ingr_schoon['recipe'] if recept not in fav_recepten and recept not in titel_lijst]
#titel_lijst = [i for n, i in enumerate(ingr_schoon['recipe']) if i not in fav_recepten and i not in ingr_schoon['recipe'].iloc[0:n]]
#titel_lijst
gelijkenis = []
for recept in titel_lijst:
    recept_lijst = list(ingr_schoon['ingredient'].loc[ingr_schoon['recipe']==recept])
    rec_matrix = count_vectorizer.transform(recept_lijst)
    cosinus = cosine_similarity(np.ones(np.size(rec_matrix.toarray())).reshape(1,-1), rec_matrix.reshape(1,-1))
    gelijkenis.append([cosinus[0][0],recept])
    
gelijkenis.sort(reverse=True)
gelijkenis[:20]


[[0.10336227882434038, 'Snelle Thaise viskoekjes met chilisaus'],
 [0.08006407690254358, "Volkorenpincho's"],
 [0.08006407690254358, "Marokkaanse' lamsbout"],
 [0.08006407690254358, 'Kerstballetjes met gesmolten kaas'],
 [0.08006407690254358, "Burrito'-schotel met knapperige tortillapuntjes"],
 [0.08006407690254358, 'Banaan met chocolade en rum'],
 [0.08006407690254358, 'Asperges koken'],
 [0.08006407690254357, 'Yoghurtmarinade met baharat'],
 [0.07734924681537618,
  'Traybake met kikkererwten, kipgehaktballetjes en garam masala'],
 [0.07665551758398331,
  'Mexicaanse maaltijdsoep van zoete aardappel met kidneybonen '],
 [0.07665551758398331, 'Carpaccio-wraps'],
 [0.07548513560963974, 'Farro met paprika-tomatensaus'],
 [0.07412493166611012,
  'Snelle noedelroerbak met groene currypasta en een eitje'],
 [0.07412493166611012, 'Aardappel-tonijnsalade met asperges'],
 [0.07308816827558576, 'Minigroenten met dragondressing'],
 [0.07308816827558574, 'Roodfruit-avocadosmoothie'],
 [0.07203648

In [154]:
aanbeveling = [titel[1] for titel in gelijkenis][:10]
aanbeveling

['Snelle Thaise viskoekjes met chilisaus',
 "Volkorenpincho's",
 "Marokkaanse' lamsbout",
 'Kerstballetjes met gesmolten kaas',
 "Burrito'-schotel met knapperige tortillapuntjes",
 'Banaan met chocolade en rum',
 'Asperges koken',
 'Yoghurtmarinade met baharat',
 'Traybake met kikkererwten, kipgehaktballetjes en garam masala',
 'Mexicaanse maaltijdsoep van zoete aardappel met kidneybonen ']

In [156]:
class Recepten: 
    
    def __init__(self, data_ingr, schoongemaakt=False): 
        # Initialisatie van de klasse met het pad naar de data en of de data schoon is 
        self.data_ingr = data_ingr
        self.schoongemaakt = schoongemaakt
        self.fav_ingr = None
        self.titel_lijst = None
        
    def laad_ingr(self):
        # Methode die de ingrediëntentabel inlaadt
        self.tabel = pd.read_csv(self.data_ingr)
        
    def aanbeveling(self, fav_recepten):
        self.fav_ingr = list(set(self.tabel['ingredient'].loc[self.tabel['recipe'].isin(fav_recepten)])) # door set worden de duplicates weggehaald
        #self.fav_ingr = np.array({self.tabel['ingredient'][i] for i in range(0, len(self.tabel)) if self.tabel['recipe'][i] in fav_recepten})
        count_vectorizer = CountVectorizer()
        self.fav_matrix = count_vectorizer.fit_transform(self.fav_ingr)
        titel_lijst = []
        [titel_lijst.append(recept) for recept in self.tabel['recipe'] if recept not in fav_recepten and recept not in titel_lijst]
        gelijkenis = []
        for recept in titel_lijst:
            recept_lijst = list(self.tabel['ingredient'].loc[self.tabel['recipe']==recept])
            rec_matrix = count_vectorizer.transform(recept_lijst)
            cosinus = cosine_similarity(np.ones(np.size(rec_matrix.toarray())).reshape(1,-1), rec_matrix.reshape(1,-1))
            gelijkenis.append([cosinus[0][0],recept])
            
        gelijkenis.sort(reverse=True)
        self.aanbeveling = [titel[1] for titel in gelijkenis][:10]
        
        return self.aanbeveling
        
recepten_klasse = Recepten('tabellen/data_ingr_clean.csv',schoongemaakt=True)
recepten_klasse.laad_ingr()

fav_recepten = recipes_wel['title'].tolist()
aanbevolen = recepten_klasse.aanbeveling(fav_recepten)
aanbevolen

['Snelle Thaise viskoekjes met chilisaus',
 "Volkorenpincho's",
 "Marokkaanse' lamsbout",
 'Kerstballetjes met gesmolten kaas',
 "Burrito'-schotel met knapperige tortillapuntjes",
 'Banaan met chocolade en rum',
 'Asperges koken',
 'Yoghurtmarinade met baharat',
 'Traybake met kikkererwten, kipgehaktballetjes en garam masala',
 'Mexicaanse maaltijdsoep van zoete aardappel met kidneybonen ']

In [185]:
ingr_schoon.loc[ingr_schoon['recipe'] == 'Snelle Thaise viskoekjes met chilisaus ']

Unnamed: 0                                   recipe  \
31220       45595  Snelle Thaise viskoekjes met chilisaus    
31221       45596  Snelle Thaise viskoekjes met chilisaus    
31222       45597  Snelle Thaise viskoekjes met chilisaus    
31223       45598  Snelle Thaise viskoekjes met chilisaus    
31225       45600  Snelle Thaise viskoekjes met chilisaus    
31226       45601  Snelle Thaise viskoekjes met chilisaus    
31227       45602  Snelle Thaise viskoekjes met chilisaus    
31228       45603  Snelle Thaise viskoekjes met chilisaus    
31229       45604  Snelle Thaise viskoekjes met chilisaus    

                 ingredient  quantity unit  
31220       verse koriander      15.0    g  
31221            rode peper      20.0    g  
31222          verse gember      10.0    g  
31223  verse haricots verts     150.0    g  
31225               vissaus      15.0    g  
31226                limoen      60.0    g  
31227            tarwebloem     120.0    g  
31228          arachideolie     230.0    g  
31229       zoete chilisaus     100.0    g

In [178]:
fav_ingr = list(set(ingr_schoon['ingredient'].loc[ingr_schoon['recipe'].isin(fav_recepten)])) 
'diepvries rauwe gepelde roze garnalen' in fav_ingr

True

In [39]:
# recept_schoon = Recepten(ingr_schoon)

# print(recept_schoon.data_frame)

AttributeError: 'Recepten' object has no attribute 'data_frame'

In [14]:
# recept_ns = Recepten(ingr_ns)

# print(recept_ns.data_frame)

       Unnamed: 0                            recipe            ingredient  \
0               0     Kruidnoten met choco-discodip         melkchocolade   
1               1     Kruidnoten met choco-discodip            kruidnoten   
2               2     Kruidnoten met choco-discodip              discodip   
3               3           Kruidnoten in marsepein      blanke marsepein   
4               4           Kruidnoten in marsepein  ongezouten roomboter   
...           ...                               ...                   ...   
49814       71804  Biefstuk met rodewijnsaus en ham             olijfolie   
49815       71805  Biefstuk met rodewijnsaus en ham           biefstukken   
49816       71806  Biefstuk met rodewijnsaus en ham                 boter   
49817       71807  Biefstuk met rodewijnsaus en ham            serranoham   
49818       71808  Biefstuk met rodewijnsaus en ham             rode wijn   

       quantity     unit  
0         100.0        g  
1         100.0      

In [15]:
recipes_schoon = recipes.dropna(subset=['title'])
recipes_schoon

Unnamed: 0  title  persons  time  \
0                            Courgette carbonara      4       20   575   
0   Mexicaanse taco's met vis en zoete aardappel      4       20   655   
0        Gegrilde-paprikasalade met feta en munt      4       15   205   
0           Viscurry met zelfgemaakte currypasta      4       20   345   
0            Spruitjesgratin met zoete aardappel      4       10   665   
..                                           ...    ...      ...   ...   
0     Rodekoolsteak met blauwaderkaas en truffel      4       15   550   
0         Vegan wraps met tofu en rodekoolsalade      4       20   670   
0                             Hachee uit de oven      4       15   365   
0                          Aardappel en zuurkool      4       15   405   
0                          Zuurkool-bonenschotel      4       15   495   

    calories                                              stars  \
0          0  https://www.ah.nl/allerhande/recept/R-R1188954...   
0          0  https://www.ah.nl/allerhande/recept/R-R1188828...   
0          0  https://www.ah.nl/allerhande/recept/R-R1188715...   
0          0  https://www.ah.nl/allerhande/recept/R-R1187967...   
0          0  https://www.ah.nl/allerhande/recept/R-R1187741...   
..       ...                                                ...   
0          0  https://www.ah.nl/allerhande/recept/R-R1189726...   
0          0  https://www.ah.nl/allerhande/recept/R-R1195491...   
0          0  https://www.ah.nl/allerhande/recept/R-R1193014...   
0          0  https://www.ah.nl/allerhande/recept/R-R758540/...   
0          0  https://www.ah.nl/allerhande/recept/R-R1189475...   

                                                  url  image  
0   https://static.ah.nl/static/recepten/img_RAM_P...    NaN  
0   https://static.ah.nl/static/recepten/img_09292...    NaN  
0   https://static.ah.nl/static/recepten/img_09094...    NaN  
0   https://static.ah.nl/static/recepten/img_08598...    NaN  
0   https://static.ah.nl/static/recepten/img_08516...    NaN  
..                                                ...    ...  
0   https://static.ah.nl/static/recepten/img_10034...    NaN  
0   https://static.ah.nl/static/recepten/img_RAM_P...    NaN  
0   https://static.ah.nl/static/recepten/img_RAM_P...    NaN  
0   https://static.ah.nl/static/recepten/img_00767...    NaN  
0   https://static.ah.nl/static/recepten/img_09892...    NaN  

[120 rows x 8 columns]

In [16]:
a= np.array([recipes_schoon['title']]) 
a 

array([[ 4,  4,  4,  4,  4,  4,  4,  4,  4, 12,  4,  4,  4,  4,  1,  4,
        20, 24, 20,  4,  4,  4,  4,  4,  4, 10, 16,  4,  4,  2,  4, 12,
         4,  8,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,
         4,  4,  4,  4,  4,  4,  4, 12,  4, 20,  4, 12, 12,  4,  4,  4,
         4,  4,  4,  8,  4,  6, 12,  4,  4,  8,  4,  4,  4,  2,  4,  4,
         4,  2,  4,  2,  4,  4,  4,  1,  2,  4,  4,  4,  4,  4,  4,  4,
         8,  4, 12,  4,  4, 20,  2,  4,  4,  4,  4,  4,  4,  4,  4,  4,
         4,  4,  4,  4,  4,  4,  4,  4]])

In [32]:
set_ingr= { ingr_schoon['ingredient'][i] for i in range(0, len(ingr_schoon)) if ingr_schoon['recipe'][i] in a}
set_ingr 

{'100% notenpasta amandel',
 'AH BASIC spaghetti',
 'AH Biologisch carpaccio met kaas, dressing en pijnboompitten',
 'Aardappel',
 'BYB red cheddar',
 'Balsajo zwarte knoflook',
 'Chioggia biet',
 'Country Cow Cheese slices',
 'De Zaanse Hoeve ongezouten roomboter',
 'De Zaanse Hoeve verse slagroom',
 'Euroma Original Spices Thai green curry',
 'Gelderse rookworst',
 'Go-Tan volkorennoedels',
 'Goudse belegen komijnekaas 48+',
 'Grand’Italia Sugocasa Erbe in fles',
 'Grand’Italia gnocchi',
 'HAK linzen in zak',
 'Hollandse bruine bonen uit pot',
 'Italiaanse roerbakgroente champignons',
 'Kaas',
 'Kipfilet',
 'Kool',
 'Kruidenmix tex mex',
 'Kühne mierikswortel in pot',
 'Peen',
 'Zalm',
 'ahornsiroop',
 'amandeldrink',
 'amandelen dry roasted',
 'amandelmeel',
 'amandelschaafsel',
 'amandelspijs',
 'ananas',
 'ansjovisfilets in olie in blik',
 'appel',
 'appelciderazijn',
 'appelmoes 0%',
 'arachideolie',
 'aspergebroccoli',
 'aubergine',
 'augurkenblokjes',
 'azijn',
 'babyromainesla